services:
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #       - /etc/localtime:/etc/localtime:ro
  #       - /etc/timezone:/etc/timezone:ro
  vms-server:
    image: app-debug
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    command: ["./startup.sh"]
    ports:
      - 8000:8000
      - 5678:5678 # debugy
    env_file:
      - .env
    volumes:
      - .:/app
    # environment:
    #   - REDIS_HOST=redis
    # depends_on:
    #   - redis